import { Pipe, PipeTransform } from '@angular/core';

@Pipe({
  name: 'customPipeDemo'
})
export class CustomPipeDemoPipe implements PipeTransform {

  transform(value: string, ...args: unknown[]): string {
    return "This text is generated by pipe : " + value;
  }

}
